spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_lecatro
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    host:  smtp.gmail.com             # servidor SMTP do Gmail
    port:  465                    # SSL 
    username: ${MAIL_USERNAME}        #dery.lecatro@gmail.com
    password: ${MAIL_PASSWORD}        # App Password de 16 caracteres
    properties:
      mail:
        smtp:
          auth: true                  # autenticação obrigatória
          ssl:
            enable: true              # encriptação TLS obrigatória
      socketFactory:
        port: 465                      # SSL em vez de starttls
        class: javax.net.ssl.SSLSocketFactory
     
logging:
  level:
    '[com.dery.lecatro]': DEBUG